### ISSUE TITLE
Unable to compile for mac catalysts targets

### ISSUE THREAD

**Issue by kgrech** [Absolucy/tracing-oslog#4]
Running of the following commands:
```
cargo +nightly build --target x86_64-apple-ios-macabi -Zbuild-std -vv
cargo +nightly build --target aarch64-apple-ios-macabi -Zbuild-std -vv
```
fails with the following error:
```
[tracing-oslog 0.1.2] error: invalid version number in '--target=arm64-apple-ios-macabi'
[tracing-oslog 0.1.2] wrapper.h:1:10: fatal error: 'os/log.h' file not found
[tracing-oslog 0.1.2] thread 'main' panicked at 'Unable to generate bindings: ClangDiagnostic("error: invalid version number in '--target=arm64-apple-ios-macabi'\nwrapper.h:1:10: fatal error: 'os/log.h' file not found\n")', build.rs:27:10
[tracing-oslog 0.1.2] note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: failed to run custom build command for `tracing-oslog v0.1.2 (/Users/kgrech/projects/github/tracing-oslog)`

Caused by:
  process didn't exit successfully: `/Users/kgrech/projects/github/tracing-oslog/target/debug/build/tracing-oslog-2738b1c7de5e969d/build-script-build` (exit status: 101)
  --- stderr
  error: invalid version number in '--target=arm64-apple-ios-macabi'
  wrapper.h:1:10: fatal error: 'os/log.h' file not found
  thread 'main' panicked at 'Unable to generate bindings: ClangDiagnostic("error: invalid version number in '--target=arm64-apple-ios-macabi'\nwrapper.h:1:10: fatal error: 'os/log.h' file not found\n")', build.rs:27:10
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
```
It looks there might be a problem invoking bindgen

**Comment by Absolucy** [comment]
Fixed by #5
